apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud
  namespace: fintech-ecosystem
  labels:
    app: fraud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud
  template:
    metadata:
      labels:
        app: fraud
    spec:
      containers:
      - name: fraud
        image: microservice:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: SERVICE_NAME
          value: "fraud"
        - name: KAFKA_BROKERS
          value: "redpanda:9092"
        - name: RABBITMQ_URL
          value: "amqp://user:password@rabbitmq:5672/"
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: fraud
  namespace: fintech-ecosystem
spec:
  selector:
    app: fraud
  ports:
  - port: 8081
    targetPort: 8081
